## Pinout generated for U20 (xc7z020clg484)
set_property -dict { PACKAGE_PIN A1    IOSTANDARD LVCMOS33 } [get_ports { pin_BOOTSPI_CS }];
set_property -dict { PACKAGE_PIN A2    IOSTANDARD LVCMOS33 } [get_ports { pin_BOOTSPI_DQ0_BMODE3 }];
set_property -dict { PACKAGE_PIN A3    IOSTANDARD LVCMOS33 } [get_ports { pin_BOOTSPI_DQ3_BMODE0 }];
set_property -dict { PACKAGE_PIN A4    IOSTANDARD LVCMOS33 } [get_ports { pin_BOOTSPI_SCK_BMODE4 }];
# set_property -dict { PACKAGE_PIN A5    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN A6    IOSTANDARD LVCMOS33 } [get_ports { pin_I2C33_SDA }];
set_property -dict { PACKAGE_PIN A7    IOSTANDARD LVCMOS33 } [get_ports { pin_SD_D0 }];
set_property -dict { PACKAGE_PIN A8    IOSTANDARD LVCMOS33 } [get_ports { pin_SD_D2 }];
# set_property -dict { PACKAGE_PIN A9    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20GNPS_MIO36_501NPadA9 }];
# set_property -dict { PACKAGE_PIN A10    IOSTANDARD LVCMOS33 } [get_ports { pin_P3V3 }];
set_property -dict { PACKAGE_PIN A11    IOSTANDARD LVCMOS33 } [get_ports { pin_JOYMISO }];
set_property -dict { PACKAGE_PIN A12    IOSTANDARD LVCMOS33 } [get_ports { pin_JOYCS }];
set_property -dict { PACKAGE_PIN A13    IOSTANDARD LVCMOS33 } [get_ports { pin_SD2_D2 }];
set_property -dict { PACKAGE_PIN A14    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU20GNPS_MIO22_501 }];
# set_property -dict { PACKAGE_PIN A15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN A16    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN A17    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN A18    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN A19    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN A20    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN A21    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN A22    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN AA1    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20HNPS_DDR_DQ26_502NPadAA1 }];
set_property -dict { PACKAGE_PIN AA2    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DM3 }];
# set_property -dict { PACKAGE_PIN AA3    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20HNPS_DDR_DQ24_502NPadAA3 }];
set_property -dict { PACKAGE_PIN AA4    IOSTANDARD LVCMOS33 } [get_ports { pin_Peripherals_BOOSTENABLE }];
# set_property -dict { PACKAGE_PIN AA5    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN AA6    IOSTANDARD LVCMOS33 } [get_ports { pin_Peripherals_LCDDHSYNC }];
set_property -dict { PACKAGE_PIN AA7    IOSTANDARD LVCMOS33 } [get_ports { pin_Peripherals_LCDDVSYNC }];
set_property -dict { PACKAGE_PIN AA8    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDBLUE4 }];
set_property -dict { PACKAGE_PIN AA9    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDBLUE5 }];
# set_property -dict { PACKAGE_PIN AA10    IOSTANDARD LVCMOS33 } [get_ports { pin_P3V3 }];
set_property -dict { PACKAGE_PIN AA11    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDGREEN7 }];
set_property -dict { PACKAGE_PIN AA12    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDGREEN5 }];
set_property -dict { PACKAGE_PIN AA13    IOSTANDARD LVCMOS33 } [get_ports { pin_I2S_BCLK }];
set_property -dict { PACKAGE_PIN AA14    IOSTANDARD LVCMOS33 } [get_ports { pin_I2S_DACSD }];
# set_property -dict { PACKAGE_PIN AA15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN AA16    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L18P_T2_33NPadAA16 }];
set_property -dict { PACKAGE_PIN AA17    IOSTANDARD LVCMOS33 } [get_ports { pin_TLV_RST }];
# set_property -dict { PACKAGE_PIN AA18    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L12N_T1_MRCC_33NPadAA18 }];
set_property -dict { PACKAGE_PIN AA19    IOSTANDARD LVCMOS33 } [get_ports { pin_LED_1R_CTRL }];
# set_property -dict { PACKAGE_PIN AA20    IOSTANDARD LVCMOS33 } [get_ports { pin_P3V3 }];
# set_property -dict { PACKAGE_PIN AA21    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L8P_T1_33NPadAA21 }];
# set_property -dict { PACKAGE_PIN AA22    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L7P_T1_33NPadAA22 }];
set_property -dict { PACKAGE_PIN AB1    IOSTANDARD LVCMOS33 } [get_ports { pin_Peripherals_LCDDDEN }];
set_property -dict { PACKAGE_PIN AB2    IOSTANDARD LVCMOS33 } [get_ports { pin_STATLED_0 }];
# set_property -dict { PACKAGE_PIN AB3    IOSTANDARD LVCMOS33 } [get_ports { pin_P3V3 }];
# set_property -dict { PACKAGE_PIN AB4    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20BNIO_L16N_T2_13NPadAB4 }];
# set_property -dict { PACKAGE_PIN AB5    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20BNIO_L16P_T2_13NPadAB5 }];
set_property -dict { PACKAGE_PIN AB6    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDRED5 }];
set_property -dict { PACKAGE_PIN AB7    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDBLUE3 }];
# set_property -dict { PACKAGE_PIN AB8    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN AB9    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDBLUE0 }];
set_property -dict { PACKAGE_PIN AB10    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDBLUE1 }];
set_property -dict { PACKAGE_PIN AB11    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDGREEN6 }];
set_property -dict { PACKAGE_PIN AB12    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDGREEN4 }];
# set_property -dict { PACKAGE_PIN AB13    IOSTANDARD LVCMOS33 } [get_ports { pin_P3V3 }];
set_property -dict { PACKAGE_PIN AB14    IOSTANDARD LVCMOS33 } [get_ports { pin_I2S_LRCLK }];
set_property -dict { PACKAGE_PIN AB15    IOSTANDARD LVCMOS33 } [get_ports { pin_I2S_ADCSD }];
# set_property -dict { PACKAGE_PIN AB16    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L18N_T2_33NPadAB16 }];
# set_property -dict { PACKAGE_PIN AB17    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L17N_T2_33NPadAB17 }];
# set_property -dict { PACKAGE_PIN AB18    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN AB19    IOSTANDARD LVCMOS33 } [get_ports { pin_JACK_DET }];
set_property -dict { PACKAGE_PIN AB20    IOSTANDARD LVCMOS33 } [get_ports { pin_LED_1G_CTRL }];
# set_property -dict { PACKAGE_PIN AB21    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L8N_T1_33NPadAB21 }];
# set_property -dict { PACKAGE_PIN AB22    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L7N_T1_33NPadAB22 }];
set_property -dict { PACKAGE_PIN B1    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DM0 }];
set_property -dict { PACKAGE_PIN B2    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQ2 }];
# set_property -dict { PACKAGE_PIN B3    IOSTANDARD LVCMOS33 } [get_ports { pin_P3V3 }];
set_property -dict { PACKAGE_PIN B4    IOSTANDARD LVCMOS33 } [get_ports { pin_UART33_TX }];
set_property -dict { PACKAGE_PIN B5    IOSTANDARD LVCMOS33 } [get_ports { pin_ZYNQ_POR }];
set_property -dict { PACKAGE_PIN B6    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_VTT_EN }];
set_property -dict { PACKAGE_PIN B7    IOSTANDARD LVCMOS33 } [get_ports { pin_SD2_D0 }];
# set_property -dict { PACKAGE_PIN B8    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN B9    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20GNPS_MIO45_501NPadB9 }];
# set_property -dict { PACKAGE_PIN B10    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20GNPS_MIO47_501NPadB10 }];
# set_property -dict { PACKAGE_PIN B11    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20GNPS_MIO43_501NPadB11 }];
set_property -dict { PACKAGE_PIN B12    IOSTANDARD LVCMOS33 } [get_ports { pin_BTN3 }];
# set_property -dict { PACKAGE_PIN B13    IOSTANDARD LVCMOS33 } [get_ports { pin_P3V3 }];
# set_property -dict { PACKAGE_PIN B14    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20GNPS_MIO37_501NPadB14 }];
# set_property -dict { PACKAGE_PIN B15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN B16    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN B17    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN B18    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN B19    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN B20    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN B21    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN B22    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN C1    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN C2    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQS0_P }];
set_property -dict { PACKAGE_PIN C3    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQ0 }];
# set_property -dict { PACKAGE_PIN C4    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20FNPS_MIO9_500NPadC4 }];
set_property -dict { PACKAGE_PIN C5    IOSTANDARD LVCMOS33 } [get_ports { pin_I2C33_SCLK }];
# set_property -dict { PACKAGE_PIN C6    IOSTANDARD LVCMOS33 } [get_ports { pin_P3V3 }];
set_property -dict { PACKAGE_PIN C7    IOSTANDARD LVCMOS33 } [get_ports { pin_BTN1 }];
set_property -dict { PACKAGE_PIN C8    IOSTANDARD LVCMOS33 } [get_ports { pin_JOYMOSI }];
set_property -dict { PACKAGE_PIN C9    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU20GNPS_SRST_B_501 }];
# set_property -dict { PACKAGE_PIN C10    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20GNPS_MIO51_501NPadC10 }];
# set_property -dict { PACKAGE_PIN C11    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN C12    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20GNPS_MIO53_501NPadC12 }];
# set_property -dict { PACKAGE_PIN C13    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20GNPS_MIO39_501NPadC13 }];
# set_property -dict { PACKAGE_PIN C14    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20GNPS_MIO49_501NPadC14 }];
# set_property -dict { PACKAGE_PIN C15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN C16    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN C17    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN C18    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN C19    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN C20    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN C21    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN C22    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN D1    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQ7 }];
set_property -dict { PACKAGE_PIN D2    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQS0_N }];
set_property -dict { PACKAGE_PIN D3    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQ6 }];
# set_property -dict { PACKAGE_PIN D4    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN D5    IOSTANDARD LVCMOS33 } [get_ports { pin_VMODE0 }];
set_property -dict { PACKAGE_PIN D6    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU20GNPS_MIO16_501 }];
set_property -dict { PACKAGE_PIN D7    IOSTANDARD LVCMOS33 } [get_ports { pin_SD2_D3 }];
# set_property -dict { PACKAGE_PIN D8    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20GNPS_MIO42_501NPadD8 }];
# set_property -dict { PACKAGE_PIN D9    IOSTANDARD LVCMOS33 } [get_ports { pin_P3V3 }];
# set_property -dict { PACKAGE_PIN D10    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20GNPS_MIO52_501NPadD10 }];
# set_property -dict { PACKAGE_PIN D11    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20GNPS_MIO48_501NPadD11 }];
# set_property -dict { PACKAGE_PIN D12    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20GNPS_MIO46_501NPadD12 }];
# set_property -dict { PACKAGE_PIN D13    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20GNPS_MIO50_501NPadD13 }];
# set_property -dict { PACKAGE_PIN D14    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN D15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN D16    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN D17    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN D18    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN D19    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN D20    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN D21    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN D22    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN E1    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQ5 }];
# set_property -dict { PACKAGE_PIN E2    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V35 }];
set_property -dict { PACKAGE_PIN E3    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQ4 }];
set_property -dict { PACKAGE_PIN E4    IOSTANDARD LVCMOS33 } [get_ports { pin_BOOTSPI_DQ2_BMODE2 }];
set_property -dict { PACKAGE_PIN E5    IOSTANDARD LVCMOS33 } [get_ports { pin_VMODE1 }];
set_property -dict { PACKAGE_PIN E6    IOSTANDARD LVCMOS33 } [get_ports { pin_RF2_IRQ }];
# set_property -dict { PACKAGE_PIN E7    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN E8    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20GNPS_MIO29_501NPadE8 }];
set_property -dict { PACKAGE_PIN E9    IOSTANDARD LVCMOS33 } [get_ports { pin_SD_CMD }];
set_property -dict { PACKAGE_PIN E10    IOSTANDARD LVCMOS33 } [get_ports { pin_SD_D1 }];
set_property -dict { PACKAGE_PIN E11    IOSTANDARD LVCMOS33 } [get_ports { pin_SD2_CMD }];
# set_property -dict { PACKAGE_PIN E12    IOSTANDARD LVCMOS33 } [get_ports { pin_P3V3 }];
# set_property -dict { PACKAGE_PIN E13    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20GNPS_MIO44_501NPadE13 }];
# set_property -dict { PACKAGE_PIN E14    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20GNPS_MIO40_501NPadE14 }];
# set_property -dict { PACKAGE_PIN E15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN E16    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN E17    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN E18    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN E19    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN E20    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN E21    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN E22    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN F1    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQ3 }];
set_property -dict { PACKAGE_PIN F2    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQ1 }];
set_property -dict { PACKAGE_PIN F3    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DRST }];
set_property -dict { PACKAGE_PIN F4    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_A13 }];
# set_property -dict { PACKAGE_PIN F5    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V35 }];
set_property -dict { PACKAGE_PIN F6    IOSTANDARD LVCMOS33 } [get_ports { pin_BOOTSPI_DQ1_BMODE1 }];
set_property -dict { PACKAGE_PIN F7    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU20FNPS_CLK_500 }];
# set_property -dict { PACKAGE_PIN F8    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20GNPS_MIO_VREF_501NPadF8 }];
set_property -dict { PACKAGE_PIN F9    IOSTANDARD LVCMOS33 } [get_ports { pin_JOYSCK }];
# set_property -dict { PACKAGE_PIN F10    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN F11    IOSTANDARD LVCMOS33 } [get_ports { pin_SD_D3 }];
set_property -dict { PACKAGE_PIN F12    IOSTANDARD LVCMOS33 } [get_ports { pin_SD2_D1 }];
# set_property -dict { PACKAGE_PIN F13    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20GNPS_MIO38_501NPadF13 }];
set_property -dict { PACKAGE_PIN F14    IOSTANDARD LVCMOS33 } [get_ports { pin_BTN4 }];
# set_property -dict { PACKAGE_PIN F15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN F16    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN F17    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN F18    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN F19    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN F20    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN F21    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN F22    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN G1    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQ15 }];
set_property -dict { PACKAGE_PIN G2    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQ13 }];
# set_property -dict { PACKAGE_PIN G3    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN G4    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_A14 }];
set_property -dict { PACKAGE_PIN G5    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_A11 }];
# set_property -dict { PACKAGE_PIN G6    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20FNPS_MIO0_500NPadG6 }];
set_property -dict { PACKAGE_PIN G7    IOSTANDARD LVCMOS33 } [get_ports { pin_UART33_RX }];
# set_property -dict { PACKAGE_PIN G8    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN G9    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN G10    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN G11    IOSTANDARD LVCMOS33 } [get_ports { pin_AX_TCLK }];
set_property -dict { PACKAGE_PIN G12    IOSTANDARD LVCMOS33 } [get_ports { pin_AX_TMS }];
set_property -dict { PACKAGE_PIN G13    IOSTANDARD LVCMOS33 } [get_ports { pin_BTN2 }];
set_property -dict { PACKAGE_PIN G14    IOSTANDARD LVCMOS33 } [get_ports { pin_AX_TDO }];
# set_property -dict { PACKAGE_PIN G15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN G16    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN G17    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN G18    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN G19    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN G20    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN G21    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN G22    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN H1    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V35 }];
set_property -dict { PACKAGE_PIN H2    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQS1_P }];
set_property -dict { PACKAGE_PIN H3    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DM1 }];
set_property -dict { PACKAGE_PIN H4    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_A12 }];
set_property -dict { PACKAGE_PIN H5    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_A9 }];
# set_property -dict { PACKAGE_PIN H6    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN H7    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_VREF }];
# set_property -dict { PACKAGE_PIN H8    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN H9    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN H10    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V8 }];
# set_property -dict { PACKAGE_PIN H11    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN H12    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN H13    IOSTANDARD LVCMOS33 } [get_ports { pin_AX_TDI }];
# set_property -dict { PACKAGE_PIN H14    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN H15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN H16    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN H17    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN H18    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN H19    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN H20    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN H21    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN H22    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN J1    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQ11 }];
set_property -dict { PACKAGE_PIN J2    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQS1_N }];
set_property -dict { PACKAGE_PIN J3    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_A10 }];
# set_property -dict { PACKAGE_PIN J4    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V35 }];
set_property -dict { PACKAGE_PIN J5    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_A8 }];
set_property -dict { PACKAGE_PIN J6    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_A7 }];
set_property -dict { PACKAGE_PIN J7    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_A6 }];
# set_property -dict { PACKAGE_PIN J8    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN J9    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN J10    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN J11    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN J12    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN J13    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN J14    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN J15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN J16    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN J17    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN J18    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN J19    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN J20    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN J21    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN J22    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN K1    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQ12 }];
# set_property -dict { PACKAGE_PIN K2    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN K3    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQ14 }];
set_property -dict { PACKAGE_PIN K4    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_A2 }];
set_property -dict { PACKAGE_PIN K5    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_A5 }];
set_property -dict { PACKAGE_PIN K6    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_A4 }];
# set_property -dict { PACKAGE_PIN K7    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V35 }];
# set_property -dict { PACKAGE_PIN K8    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN K9    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V8 }];
# set_property -dict { PACKAGE_PIN K10    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN K11    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V8 }];
# set_property -dict { PACKAGE_PIN K12    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN K13    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN K14    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN K15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN K16    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN K17    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN K18    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN K19    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN K20    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN K21    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN K22    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN L1    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQ9 }];
set_property -dict { PACKAGE_PIN L2    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQ10 }];
set_property -dict { PACKAGE_PIN L3    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQ8 }];
set_property -dict { PACKAGE_PIN L4    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_A3 }];
# set_property -dict { PACKAGE_PIN L5    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN L6    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_BA1 }];
set_property -dict { PACKAGE_PIN L7    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_BA0 }];
# set_property -dict { PACKAGE_PIN L8    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN L9    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN L10    IOSTANDARD LVCMOS33 } [get_ports { pin_Power_VCCAUX }];
# set_property -dict { PACKAGE_PIN L11    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN L12    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN L13    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN L14    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN L15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN L16    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN L17    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN L18    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN L19    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN L20    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN L21    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN L22    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN M1    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20HNPS_DDR_DQ16_502NPadM1 }];
# set_property -dict { PACKAGE_PIN M2    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20HNPS_DDR_DQ22_502NPadM2 }];
# set_property -dict { PACKAGE_PIN M3    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V35 }];
set_property -dict { PACKAGE_PIN M4    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_A0 }];
set_property -dict { PACKAGE_PIN M5    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_A1 }];
set_property -dict { PACKAGE_PIN M6    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_BA2 }];
# set_property -dict { PACKAGE_PIN M7    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU20HNPS_DDR_VRN_502 }];
# set_property -dict { PACKAGE_PIN M8    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN M9    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V8 }];
# set_property -dict { PACKAGE_PIN M10    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN M11    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN M12    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN M13    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN M14    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN M15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN M16    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN M17    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN M18    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN M19    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN M20    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN M21    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN M22    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN N1    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN N2    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQS2_P }];
# set_property -dict { PACKAGE_PIN N3    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20HNPS_DDR_DQ18_502NPadN3 }];
set_property -dict { PACKAGE_PIN N4    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_CK_P }];
set_property -dict { PACKAGE_PIN N5    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_CK_N }];
# set_property -dict { PACKAGE_PIN N6    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V35 }];
# set_property -dict { PACKAGE_PIN N7    IOSTANDARD LVCMOS33 } [get_ports { pin_NetNU20HNPS_DDR_VRP_502 }];
# set_property -dict { PACKAGE_PIN N8    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN N9    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN N10    IOSTANDARD LVCMOS33 } [get_ports { pin_Power_VCCAUX }];
# set_property -dict { PACKAGE_PIN N11    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN N12    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN N13    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN N14    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN N15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN N16    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN N17    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN N18    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN N19    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN N20    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN N21    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN N22    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN P1    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DM2 }];
set_property -dict { PACKAGE_PIN P2    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQS2_N }];
set_property -dict { PACKAGE_PIN P3    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_CAS }];
# set_property -dict { PACKAGE_PIN P4    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN P5    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_ODT }];
set_property -dict { PACKAGE_PIN P6    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_CS }];
# set_property -dict { PACKAGE_PIN P7    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_VREF }];
# set_property -dict { PACKAGE_PIN P8    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN P9    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V8 }];
# set_property -dict { PACKAGE_PIN P10    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN P11    IOSTANDARD LVCMOS33 } [get_ports { pin_Power_VCCAUX }];
# set_property -dict { PACKAGE_PIN P12    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN P13    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN P14    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN P15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN P16    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN P17    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN P18    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN P19    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN P20    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN P21    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN P22    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN R1    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20HNPS_DDR_DQ23_502NPadR1 }];
# set_property -dict { PACKAGE_PIN R2    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V35 }];
# set_property -dict { PACKAGE_PIN R3    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20HNPS_DDR_DQ20_502NPadR3 }];
set_property -dict { PACKAGE_PIN R4    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_WE }];
set_property -dict { PACKAGE_PIN R5    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_RAS }];
# set_property -dict { PACKAGE_PIN R6    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20BNIO_L19P_T3_13NPadR6 }];
# set_property -dict { PACKAGE_PIN R7    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20BNIO_0_13NPadR7 }];
# set_property -dict { PACKAGE_PIN R8    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN R9    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN R10    IOSTANDARD LVCMOS33 } [get_ports { pin_Power_VCCAUX }];
# set_property -dict { PACKAGE_PIN R11    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN R12    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V8 }];
# set_property -dict { PACKAGE_PIN R13    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN R14    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V0 }];
# set_property -dict { PACKAGE_PIN R15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN R16    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN R17    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN R18    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN R19    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN R20    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN R21    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN R22    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN T1    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20HNPS_DDR_DQ19_502NPadT1 }];
# set_property -dict { PACKAGE_PIN T2    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20HNPS_DDR_DQ21_502NPadT2 }];
# set_property -dict { PACKAGE_PIN T3    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20HNPS_DDR_DQ17_502NPadT3 }];
# set_property -dict { PACKAGE_PIN T4    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20BNIO_L20P_T3_13NPadT4 }];
# set_property -dict { PACKAGE_PIN T5    IOSTANDARD LVCMOS33 } [get_ports { pin_P3V3 }];
# set_property -dict { PACKAGE_PIN T6    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20BNIO_L19N_T3_VREF_13NPadT6 }];
# set_property -dict { PACKAGE_PIN T7    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V8 }];
# set_property -dict { PACKAGE_PIN T8    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V8 }];
# set_property -dict { PACKAGE_PIN T9    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V8 }];
# set_property -dict { PACKAGE_PIN T10    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V8 }];
set_property -dict { PACKAGE_PIN T11    IOSTANDARD LVCMOS33 } [get_ports { pin_PROGRAM_B }];
# set_property -dict { PACKAGE_PIN T12    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20ANDONE_0NPadT12 }];
# set_property -dict { PACKAGE_PIN T13    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN T14    IOSTANDARD LVCMOS33 } [get_ports { pin_INIT_B }];
# set_property -dict { PACKAGE_PIN T15    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN T16    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN T17    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN T18    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN T19    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN T20    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN T21    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L1P_T0_33NPadT21 }];
# set_property -dict { PACKAGE_PIN T22    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L2P_T0_33NPadT22 }];
# set_property -dict { PACKAGE_PIN U1    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20HNPS_DDR_DQ25_502NPadU1 }];
# set_property -dict { PACKAGE_PIN U2    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20HNPS_DDR_DQ27_502NPadU2 }];
# set_property -dict { PACKAGE_PIN U3    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN U4    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20BNIO_L20N_T3_13NPadU4 }];
# set_property -dict { PACKAGE_PIN U5    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20BNIO_L22N_T3_13NPadU5 }];
# set_property -dict { PACKAGE_PIN U6    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20BNIO_L22P_T3_13NPadU6 }];
# set_property -dict { PACKAGE_PIN U7    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20BNIO_25_13NPadU7 }];
# set_property -dict { PACKAGE_PIN U8    IOSTANDARD LVCMOS33 } [get_ports { pin_P3V3 }];
set_property -dict { PACKAGE_PIN U9    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDGREEN2 }];
set_property -dict { PACKAGE_PIN U10    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDGREEN3 }];
set_property -dict { PACKAGE_PIN U11    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDGREEN0 }];
set_property -dict { PACKAGE_PIN U12    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDGREEN1 }];
# set_property -dict { PACKAGE_PIN U13    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN U14    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_25_33NPadU14 }];
# set_property -dict { PACKAGE_PIN U15    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L15P_T2_DQS_33NPadU15 }];
# set_property -dict { PACKAGE_PIN U16    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L15N_T2_DQS_33NPadU16 }];
# set_property -dict { PACKAGE_PIN U17    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L16P_T2_33NPadU17 }];
# set_property -dict { PACKAGE_PIN U18    IOSTANDARD LVCMOS33 } [get_ports { pin_P3V3 }];
# set_property -dict { PACKAGE_PIN U19    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_0_33NPadU19 }];
# set_property -dict { PACKAGE_PIN U20    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L5P_T0_33NPadU20 }];
# set_property -dict { PACKAGE_PIN U21    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L1N_T0_33NPadU21 }];
# set_property -dict { PACKAGE_PIN U22    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L2N_T0_33NPadU22 }];
# set_property -dict { PACKAGE_PIN V1    IOSTANDARD LVCMOS33 } [get_ports { pin_P1V35 }];
set_property -dict { PACKAGE_PIN V2    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQS3_P }];
set_property -dict { PACKAGE_PIN V3    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_CKE }];
# set_property -dict { PACKAGE_PIN V4    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20BNIO_L21N_T3_DQS_13NPadV4 }];
# set_property -dict { PACKAGE_PIN V5    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20BNIO_L21P_T3_DQS_13NPadV5 }];
# set_property -dict { PACKAGE_PIN V6    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN V7    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20BNIO_L23P_T3_13NPadV7 }];
set_property -dict { PACKAGE_PIN V8    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDRED3 }];
set_property -dict { PACKAGE_PIN V9    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDRED0 }];
set_property -dict { PACKAGE_PIN V10    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDRED1 }];
# set_property -dict { PACKAGE_PIN V11    IOSTANDARD LVCMOS33 } [get_ports { pin_P3V3 }];
set_property -dict { PACKAGE_PIN V12    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDRED7 }];
# set_property -dict { PACKAGE_PIN V13    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L20P_T3_33NPadV13 }];
# set_property -dict { PACKAGE_PIN V14    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L19P_T3_33NPadV14 }];
# set_property -dict { PACKAGE_PIN V15    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L19N_T3_VREF_33NPadV15 }];
# set_property -dict { PACKAGE_PIN V16    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN V17    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L16N_T2_33NPadV17 }];
# set_property -dict { PACKAGE_PIN V18    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L6P_T0_33NPadV18 }];
# set_property -dict { PACKAGE_PIN V19    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L6N_T0_VREF_33NPadV19 }];
# set_property -dict { PACKAGE_PIN V20    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L5N_T0_33NPadV20 }];
# set_property -dict { PACKAGE_PIN V21    IOSTANDARD LVCMOS33 } [get_ports { pin_P3V3 }];
# set_property -dict { PACKAGE_PIN V22    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L3P_T0_DQS_33NPadV22 }];
# set_property -dict { PACKAGE_PIN W1    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20HNPS_DDR_DQ28_502NPadW1 }];
set_property -dict { PACKAGE_PIN W2    IOSTANDARD LVCMOS33 } [get_ports { pin_DDR3_DQS3_N }];
# set_property -dict { PACKAGE_PIN W3    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20HNPS_DDR_DQ30_502NPadW3 }];
# set_property -dict { PACKAGE_PIN W4    IOSTANDARD LVCMOS33 } [get_ports { pin_P3V3 }];
# set_property -dict { PACKAGE_PIN W5    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20BNIO_L24N_T3_13NPadW5 }];
# set_property -dict { PACKAGE_PIN W6    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20BNIO_L24P_T3_13NPadW6 }];
# set_property -dict { PACKAGE_PIN W7    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20BNIO_L23N_T3_13NPadW7 }];
set_property -dict { PACKAGE_PIN W8    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDRED2 }];
# set_property -dict { PACKAGE_PIN W9    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN W10    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDRED4 }];
# set_property -dict { PACKAGE_PIN W11    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20BNIO_L3P_T0_DQS_13NPadW11 }];
set_property -dict { PACKAGE_PIN W12    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDRED6 }];
# set_property -dict { PACKAGE_PIN W13    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L20N_T3_33NPadW13 }];
# set_property -dict { PACKAGE_PIN W14    IOSTANDARD LVCMOS33 } [get_ports { pin_P3V3 }];
set_property -dict { PACKAGE_PIN W15    IOSTANDARD LVCMOS33 } [get_ports { pin_IMU_INT1 }];
# set_property -dict { PACKAGE_PIN W16    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L14P_T2_SRCC_33NPadW16 }];
# set_property -dict { PACKAGE_PIN W17    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L13P_T2_MRCC_33NPadW17 }];
# set_property -dict { PACKAGE_PIN W18    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L13N_T2_MRCC_33NPadW18 }];
# set_property -dict { PACKAGE_PIN W19    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN W20    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L4P_T0_33NPadW20 }];
# set_property -dict { PACKAGE_PIN W21    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L4N_T0_33NPadW21 }];
# set_property -dict { PACKAGE_PIN W22    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L3N_T0_DQS_33NPadW22 }];
# set_property -dict { PACKAGE_PIN Y1    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20HNPS_DDR_DQ31_502NPadY1 }];
# set_property -dict { PACKAGE_PIN Y2    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
# set_property -dict { PACKAGE_PIN Y3    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20HNPS_DDR_DQ29_502NPadY3 }];
# set_property -dict { PACKAGE_PIN Y4    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20BNIO_L18P_T2_13NPadY4 }];
set_property -dict { PACKAGE_PIN Y5    IOSTANDARD LVCMOS33 } [get_ports { pin_Peripherals_LCDDCLK }];
set_property -dict { PACKAGE_PIN Y6    IOSTANDARD LVCMOS33 } [get_ports { pin_Peripherals_LCDDDISP }];
# set_property -dict { PACKAGE_PIN Y7    IOSTANDARD LVCMOS33 } [get_ports { pin_P3V3 }];
set_property -dict { PACKAGE_PIN Y8    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDBLUE6 }];
set_property -dict { PACKAGE_PIN Y9    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDBLUE7 }];
set_property -dict { PACKAGE_PIN Y10    IOSTANDARD LVCMOS33 } [get_ports { pin_LCDBLUE2 }];
# set_property -dict { PACKAGE_PIN Y11    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20BNIO_L10P_T1_13NPadY11 }];
# set_property -dict { PACKAGE_PIN Y12    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
set_property -dict { PACKAGE_PIN Y13    IOSTANDARD LVCMOS33 } [get_ports { pin_I2S_MCLK }];
set_property -dict { PACKAGE_PIN Y14    IOSTANDARD LVCMOS33 } [get_ports { pin_TEMPO_SW }];
set_property -dict { PACKAGE_PIN Y15    IOSTANDARD LVCMOS33 } [get_ports { pin_IMU_INT2 }];
# set_property -dict { PACKAGE_PIN Y16    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L14N_T2_SRCC_33NPadY16 }];
# set_property -dict { PACKAGE_PIN Y17    IOSTANDARD LVCMOS33 } [get_ports { pin_P3V3 }];
# set_property -dict { PACKAGE_PIN Y18    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L12P_T1_MRCC_33NPadY18 }];
set_property -dict { PACKAGE_PIN Y19    IOSTANDARD LVCMOS33 } [get_ports { pin_LED_1B_CTRL }];
# set_property -dict { PACKAGE_PIN Y20    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L9P_T1_DQS_33NPadY20 }];
# set_property -dict { PACKAGE_PIN Y21    IOSTANDARD LVCMOS33 } [get_ports { pin_unconnectedNU20CNIO_L9N_T1_DQS_33NPadY21 }];
# set_property -dict { PACKAGE_PIN Y22    IOSTANDARD LVCMOS33 } [get_ports { pin_GND }];
