# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mihir/Prism/hardware/shiftBRAM/shiftBRAM.xci
# IP: The module: 'shiftBRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mihir/Prism/hardware/shiftBRAM/shiftBRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shiftBRAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/mihir/Prism/hardware/shiftBRAM/shiftBRAM.xci
# IP: The module: 'shiftBRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mihir/Prism/hardware/shiftBRAM/shiftBRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shiftBRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
