# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constrainsts_1.xdc

# IP: ip/singlePortBlock18/singlePortBlock18.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singlePortBlock18 || ORIG_REF_NAME==singlePortBlock18} -quiet] -quiet

# IP: ip/dualPortBlock18/dualPortBlock18.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dualPortBlock18 || ORIG_REF_NAME==dualPortBlock18} -quiet] -quiet

# IP: ip/DualPortBlock16/DualPortBlock16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DualPortBlock16 || ORIG_REF_NAME==DualPortBlock16} -quiet] -quiet

# IP: ip/dualPortBlockAXI18/dualPortBlockAXI18.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==dualPortBlockAXI18 || ORIG_REF_NAME==dualPortBlockAXI18} -quiet] -quiet

# IP: ip/programBlock16/programBlock16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==programBlock16 || ORIG_REF_NAME==programBlock16} -quiet] -quiet

# XDC: /home/mihir/Prism/hardware/fpga_design/fpga_design.gen/sources_1/ip/singlePortBlock18/singlePortBlock18_ooc.xdc

# XDC: /home/mihir/Prism/hardware/fpga_design/fpga_design.gen/sources_1/ip/dualPortBlock18/dualPortBlock18_ooc.xdc

# XDC: /home/mihir/Prism/hardware/fpga_design/fpga_design.gen/sources_1/ip/DualPortBlock16/DualPortBlock16_ooc.xdc

# XDC: /home/mihir/Prism/hardware/fpga_design/fpga_design.gen/sources_1/ip/dualPortBlockAXI18/dualPortBlockAXI18_ooc.xdc

# XDC: /home/mihir/Prism/hardware/fpga_design/fpga_design.gen/sources_1/ip/programBlock16/programBlock16_ooc.xdc
