# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# IP: ip/singlePortBlock18/singlePortBlock18.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==singlePortBlock18 || ORIG_REF_NAME==singlePortBlock18} -quiet] -quiet

# XDC: /home/mihir/Prism/hardware/fpga_design/fpga_design.gen/sources_1/ip/singlePortBlock18/singlePortBlock18_ooc.xdc
