# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/mihir/Prism/hardware/fpga_design/fpga_design.runs/synth_1/processor.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_msg_config  -id {Synth 8-327}  -string {{WARNING: [Synth 8-327] inferring latch for variable 'temp_reg' [/home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/new/alu.v:23]}}  -suppress 
set_msg_config  -id {Vivado 12-508}  -new_severity {CRITICAL WARNING} 
set_msg_config  -id {Runs 36-337}  -string {{WARNING: [Runs 36-337] The following IPs are either missing output products or output products are not up-to-date for Simulation target. Since these IPs are locked, no update to the output products can be done. 
Please select 'Report IP Status' from the 'Tools/Report' menu or run Tcl command 'report_ip_status' for more information.
/home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/ip/singlePortBlock18/singlePortBlock18.xci
/home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/ip/dualPortBlock18/dualPortBlock18.xci
/home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/ip/DualPortBlock16/DualPortBlock16.xci
/home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/ip/dualPortBlockAXI18/dualPortBlockAXI18.xci
/home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/ip/programBlock16/programBlock16.xci}}  -suppress 
set_msg_config  -id {Common 17-69}  -string {{ERROR: [Common 17-69] Command failed: File '/home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/new/sub.v' does not exist}}  -suppress 
set_msg_config  -id {Runs 36-337}  -string {{WARNING: [Runs 36-337] The following IPs are either missing output products or output products are not up-to-date for Synthesis target. Since these IPs are locked, no update to the output products can be done. 
Please select 'Report IP Status' from the 'Tools/Report' menu or run Tcl command 'report_ip_status' for more information.
/home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/ip/singlePortBlock18/singlePortBlock18.xci
/home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/ip/dualPortBlock18/dualPortBlock18.xci
/home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/ip/DualPortBlock16/DualPortBlock16.xci
/home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/ip/dualPortBlockAXI18/dualPortBlockAXI18.xci
/home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/ip/programBlock16/programBlock16.xci}}  -suppress 
set_msg_config  -id {Runs 36-271}  -string {{CRITICAL WARNING: [Runs 36-271] Incremental checkpoint part, xc7z020clg484-3, does not match run part, xc7z020clg484-2.}}  -suppress 
set_msg_config  -id {Board 49-26}  -string {{WARNING: [Board 49-26] cannot add Board Part xilinx.com:zcu208ld:part0:2.0 available at /home/mihir/xilinx/Vivado/2024.2/data/xhub/boards/XilinxBoardStore/boards/Xilinx/zcu208ld/production/2.0/board.xml as part xczu58dr-fsvg1517-2-i specified in board_part file is either invalid or not available}}  -suppress 
set_msg_config  -id {Board 49-26}  -string {{WARNING: [Board 49-26] cannot add Board Part xilinx.com:zcu216ld:part0:2.0 available at /home/mihir/xilinx/Vivado/2024.2/data/xhub/boards/XilinxBoardStore/boards/Xilinx/zcu216ld/production/2.0/board.xml as part xczu59dr-ffvf1760-2-i specified in board_part file is either invalid or not available}}  -suppress 
set_msg_config  -id {IP_Flow 19-2162}  -string {{WARNING: [IP_Flow 19-2162] IP 'singlePortBlock18' is locked:
* Current project part 'xc7z020clg484-2' and the part 'xc7z020clg484-3' used to customize the IP 'singlePortBlock18' do not match.}}  -suppress 
set_msg_config  -id {IP_Flow 19-4067}  -string {{WARNING: [IP_Flow 19-4067] Ignoring invalid widget type specified checkbox.Providing a default widget}}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7z020clg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/mihir/Prism/hardware/fpga_design/fpga_design.cache/wt [current_project]
set_property parent.project_path /home/mihir/Prism/hardware/fpga_design/fpga_design.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/mihir/Prism/hardware/fpga_design/fpga_design.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  /home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/new/thread.v
  /home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/new/thread_modules/barrelShifter.v
  /home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/new/thread_modules/instructionDecode.v
  /home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/new/thread_modules/registerFIle.v
  /home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/new/thread_modules/alu.v
  /home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/new/thread_modules/flags.v
  /home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/new/thread_modules/pc.v
  /home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/new/thread_modules/opSel.v
  /home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/new/core.v
  /home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/new/thread_modules/smolBarrelShift.v
  /home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/new/processor.v
}
read_ip -quiet /home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/ip/singlePortBlock18/singlePortBlock18.xci
set_property used_in_implementation false [get_files -all /home/mihir/Prism/hardware/fpga_design/fpga_design.gen/sources_1/ip/singlePortBlock18/singlePortBlock18_ooc.xdc]

read_ip -quiet /home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/ip/dualPortBlock18/dualPortBlock18.xci
set_property used_in_implementation false [get_files -all /home/mihir/Prism/hardware/fpga_design/fpga_design.gen/sources_1/ip/dualPortBlock18/dualPortBlock18_ooc.xdc]

read_ip -quiet /home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/ip/DualPortBlock16/DualPortBlock16.xci
set_property used_in_implementation false [get_files -all /home/mihir/Prism/hardware/fpga_design/fpga_design.gen/sources_1/ip/DualPortBlock16/DualPortBlock16_ooc.xdc]

read_ip -quiet /home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/ip/dualPortBlockAXI18/dualPortBlockAXI18.xci
set_property used_in_implementation false [get_files -all /home/mihir/Prism/hardware/fpga_design/fpga_design.gen/sources_1/ip/dualPortBlockAXI18/dualPortBlockAXI18_ooc.xdc]

read_ip -quiet /home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/sources_1/ip/programBlock16/programBlock16.xci
set_property used_in_implementation false [get_files -all /home/mihir/Prism/hardware/fpga_design/fpga_design.gen/sources_1/ip/programBlock16/programBlock16_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/constrs_1/new/constrainsts_1.xdc
set_property used_in_implementation false [get_files /home/mihir/Prism/hardware/fpga_design/fpga_design.srcs/constrs_1/new/constrainsts_1.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top processor -part xc7z020clg484-2 -flatten_hierarchy none -gated_clock_conversion auto -incremental_mode off
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef processor.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file processor_utilization_synth.rpt -pb processor_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
